# Generated by Django 4.2.6 on 2023-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='cateqoriya adi')),
            ],
            options={
                'verbose_name': 'cateqoriya adi',
                'verbose_name_plural': 'cateqoriya adlari',
                'ordering': ('name',),
            },
        ),
    ]
