# Generated by Django 4.2.6 on 2023-10-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
            ],
            options={
                'verbose_name': 'servis',
                'verbose_name_plural': 'servisler',
                'ordering': ('category',),
            },
        ),
    ]
