# Generated by Django 4.2.6 on 2023-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_our_services_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='our_service',
        ),
        migrations.AlterModelOptions(
            name='our_services',
            options={'ordering': ('name',), 'verbose_name': 'servis', 'verbose_name_plural': 'servisler'},
        ),
        migrations.RemoveField(
            model_name='our_services',
            name='category',
        ),
        migrations.AddField(
            model_name='our_services',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
