# Generated by Django 4.2.6 on 2023-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('mail', models.CharField(max_length=255, verbose_name='mail')),
                ('tel', models.IntegerField(max_length=255, verbose_name='telefon nomresi')),
                ('service', models.CharField(max_length=255, verbose_name='xidmet')),
                ('mesage', models.TextField(verbose_name='mesage')),
            ],
        ),
    ]
