# Generated by Django 4.2.6 on 2023-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('name',), 'verbose_name': 'basliq', 'verbose_name_plural': 'basliqlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name',), 'verbose_name': 'ad', 'verbose_name_plural': 'adlar'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mesage',
            field=models.CharField(max_length=255, verbose_name='mesage'),
        ),
    ]
