# Generated by Django 4.2.6 on 2023-10-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.our_services'),
        ),
    ]
