# Generated by Django 4.2.6 on 2023-10-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_contact_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
