# Generated by Django 4.2.6 on 2023-10-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('mail', models.CharField(max_length=255, verbose_name='mail')),
                ('tel', models.IntegerField(max_length=255, verbose_name='telefon nomresi')),
                ('mesage', models.CharField(max_length=255, verbose_name='mesage')),
                ('contact_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.our_services')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'adlar',
                'ordering': ('name',),
            },
        ),
    ]
