# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_service',
            field=models.CharField(blank=True, choices=[('temir', 'Təmir'), ('berpa', 'Bərpa'), ('salam', 'Salam'), ('sagol', 'Sagol')], max_length=255, null=True),
        ),
    ]
