# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_contact_contact_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
