# Generated by Django 4.2.6 on 2023-11-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_contact_mesage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAINDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon nomresi')),
                ('location', models.CharField(max_length=255, verbose_name='mekan')),
                ('mesage', models.CharField(max_length=255, verbose_name='mesage')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('map_url', models.TextField(blank=True, null=True, verbose_name='xerite')),
            ],
            options={
                'verbose_name': 'esas detal',
                'verbose_name_plural': 'esas detallar',
                'ordering': ('email',),
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel',
            field=models.IntegerField(verbose_name='telefon nomresi'),
        ),
    ]
