# Generated by Django 4.2.6 on 2023-11-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_maindetails_alter_contact_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindetails',
            name='mesage',
        ),
    ]
