# Generated by Django 4.2.6 on 2023-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_remove_maindetails_mesage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=255, verbose_name='Sosial media hesabi')),
                ('social_link', models.TextField(verbose_name='Sosial media linki')),
            ],
            options={
                'verbose_name': 'Sosial media hesabi',
                'verbose_name_plural': 'Sosial media hesablari',
                'ordering': ('social_name',),
            },
        ),
    ]
