# Generated by Django 4.2.6 on 2023-11-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_name',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok')], max_length=255, verbose_name='Sosial media hesabi'),
        ),
    ]
